@isTest
public class helloWorldTest {
    
    @isTest
    public Static void testImprimeQlkMensagem(){
        
        helloWorld chamaClasse = new helloWorld();
        chamaClasse.imprimeQlkMensagem('ola',3213,'joao');
        chamaClasse.imprimeDay(0);
        chamaClasse.imprimeDay(1);
        chamaClasse.imprimeDay(33333);
        chamaClasse.imprimeDay('Dom');
        chamaClasse.imprimeDay('Seg');
        chamaClasse.imprimeDay('Ter');
        chamaClasse.imprimeDay('Ters');
        chamaClasse.primeiroMetodo();
        
    }
    
}